### ISSUE TITLE
Cannot find module '@featbit/react-native-sdk' or its corresponding type declarations.

### ISSUE THREAD

**Issue by alexey-ulyanov** [featbit/featbit-react-native-sdk#1]
Hello @cosmos-explorer! Is it possible to fix type declarations for the SDK?

<img width="1062" alt="Screenshot 2024-09-10 at 12 20 55" src="https://github.com/user-attachments/assets/3601706d-9a88-48e0-8722-9ad1fe2ad00f">

**Comment by alexey-ulyanov** [comment]
I found that a "dist" folder doesn't exist when I installed @featbit/react-native-sdk

**Comment by cosmos-explorer** [comment]
Hi @alexey-ulyanov Sorry for the late reply, We didn't get the notification from Github.

Have you tried to remove @featbit/react-native-sdk from node_modules and install again? it's not normal to not having `dist` folder.

**Comment by alexey-ulyanov** [comment]
Hi @cosmos-explorer, yes, I tried it but it does not work. Unfortunately, I can't open PR here :(
I think the problem can be in `publish-npm.yml`:

<img width="538" alt="Screenshot 2024-09-18 at 13 50 53" src="https://github.com/user-attachments/assets/0635bfb2-5c25-4ef7-81d0-dc5acf33bf27">

**Comment by cosmos-explorer** [comment]
@alexey-ulyanov Thank you for pointing out this, I just made a commit https://github.com/featbit/featbit-react-native-sdk/commit/cc017e76ca6c22bdd80073b301fc3dd0f0fb2619 and published a new version 1.0.2
